### ISSUE TITLE
model training failed

### ISSUE THREAD

**Issue by yaow1004** [xtanh/ProStab#5]
Dear @xtanh 

After I used your fixed train.yaml file -- following the closed issue: https://github.com/xtanh/ProStab/issues/1.

I still face to the same Error:

**Traceback (most recent call last):
  File "test.py", line 35, in main
    return test(config)
  File "./ProStab/prostab/testing_pipeline.py", line 36, in test
    datamodule, pl_module, logger, callbacks = utils.common_pipeline(config)
  File "./ProStab/prostab/utils/__init__.py", line 218, in common_pipeline
    pl_module: LightningModule = instantiate_from_config(cfg=config.task, group='task')
  File "./ProStab/prostab/utils/config.py", line 123, in instantiate_from_config
    return target_cls(cfg)
TypeError: __init__() missing 2 required positional arguments: 'criterion' and 'optimizer'**

Could you help check what else should fixed? 

Thank you very much!
y.

**Comment by xtanh** [comment]
> Dear [@xtanh](https://github.com/xtanh)
> 
> After I used your fixed train.yaml file -- following the closed issue: [#1](https://github.com/xtanh/ProStab/issues/1).
> 
> I still face to the same Error:
> 
> **Traceback (most recent call last): File "test.py", line 35, in main return test(config) File "./ProStab/prostab/testing_pipeline.py", line 36, in test datamodule, pl_module, logger, callbacks = utils.common_pipeline(config) File "./ProStab/prostab/utils/init.py", line 218, in common_pipeline pl_module: LightningModule = instantiate_from_config(cfg=config.task, group='task') File "./ProStab/prostab/utils/config.py", line 123, in instantiate_from_config return target_cls(cfg) TypeError: init() missing 2 required positional arguments: 'criterion' and 'optimizer'**
> 
> Could you help check what else should fixed?
> 
> Thank you very much! y.

fixed.

**Comment by xtanh** [comment]
> > > Dear [@xtanh](https://github.com/xtanh)
> > > After I used your fixed train.yaml file -- following the closed issue: [#1](https://github.com/xtanh/ProStab/issues/1).
> > > I still face to the same Error:
> > > **Traceback (most recent call last): File "test.py", line 35, in main return test(config) File "./ProStab/prostab/testing_pipeline.py", line 36, in test datamodule, pl_module, logger, callbacks = utils.common_pipeline(config) File "./ProStab/prostab/utils/init.py", line 218, in common_pipeline pl_module: LightningModule = instantiate_from_config(cfg=config.task, group='task') File "./ProStab/prostab/utils/config.py", line 123, in instantiate_from_config return target_cls(cfg) TypeError: init() missing 2 required positional arguments: 'criterion' and 'optimizer'**
> > > Could you help check what else should fixed?
> > > Thank you very much! y.
> > 
> > 
> > fixed.
> 
> Hi,
> 
> Thanks a lot for the reply and fixing. However, I just used the fixed train.yaml file to run the training. But I still got the same error. May I kindly ask if there is any other config files or scripts or model weights -- I need to modify? I strictly followed you readme to download and install things. Additionally, I got the same error when I try to train spurs..
> 
> y

sorry, just use "python train.py" to train the model. if you have any question ,feel free to ask.

**Comment by yaow1004** [comment]
> > > > Dear [@xtanh](https://github.com/xtanh)
> > > > After I used your fixed train.yaml file -- following the closed issue: [#1](https://github.com/xtanh/ProStab/issues/1).
> > > > I still face to the same Error:
> > > > **Traceback (most recent call last): File "test.py", line 35, in main return test(config) File "./ProStab/prostab/testing_pipeline.py", line 36, in test datamodule, pl_module, logger, callbacks = utils.common_pipeline(config) File "./ProStab/prostab/utils/init.py", line 218, in common_pipeline pl_module: LightningModule = instantiate_from_config(cfg=config.task, group='task') File "./ProStab/prostab/utils/config.py", line 123, in instantiate_from_config return target_cls(cfg) TypeError: init() missing 2 required positional arguments: 'criterion' and 'optimizer'**
> > > > Could you help check what else should fixed?
> > > > Thank you very much! y.
> > > 
> > > 
> > > fixed.
> > 
> > 
> > Hi,
> > Thanks a lot for the reply and fixing. However, I just used the fixed train.yaml file to run the training. But I still got the same error. May I kindly ask if there is any other config files or scripts or model weights -- I need to modify? I strictly followed you readme to download and install things. Additionally, I got the same error when I try to train spurs..
> > y
> 
> sorry, just use "python train.py" to train the model. if you have any question ,feel free to ask.

Thank you!

I used your updated train.py. Also I only use the **python train.py** to do the training. However, still the same error...

**Comment by xtanh** [comment]
> Hi,
> 
> Thank you. I have even re-installed the entire ProStab code (from your just updated version), and re-downloaded all the model weights (from ProteinMPNN). But, I still got the same error...

Could you provide me with the full error message, including the code you ran?

**Comment by xtanh** [comment]
ProStab/
├── data/
│   ├── checkpoints/
│   │   └── ThermoMPNN/
│   │       └── vanilla_model_weights/
│   │           └── v_48_020.pt (20-25MB)
│   └── dataset/
│       └── megascale/
│           └── Tsuboyama2023_Dataset2_Dataset3_20230416.csv
├── configs/
├── prostab/
└── train.py
Based on the error message _pickle.UnpicklingError: invalid load key, '\x0a', it appears that the ProteinMPNN weight file is corrupted or incomplete.
Please re-download the ProteinMPNN weights.
After re-downloading the weight file, please try running python train.py again.

**Comment by xtanh** [comment]
> [ProStab_train_error.txt](https://github.com/user-attachments/files/22559593/ProStab_train_error.txt)
> 
> Please find the full error message in the attachment.
> 
> For the code, I only used the ProStab model which you updated approx. 40min ago. I then downloaded the ProteinMPNN model weights from: https://github.com/dauparas/ProteinMPNN/blob/main/vanilla_model_weights/v_48_020.pt. --> to put in the created ProStab/data/checkpoints/ThermoMPNN/vanilla_model_weights/ folder.
> 
> Moreover, I also added the megascale "Tsuboyama2023_Dataset2_Dataset3_20230416.csv" into: ProStab/data/dataset/megascale/ folder.
> 
> Thank you!

ProStab/
├── data/
│ ├── checkpoints/
│ │ └── ThermoMPNN/
│ │ └── vanilla_model_weights/
│ │ └── v_48_020.pt 
│ └── dataset/
│ └── megascale/
│ └── Tsuboyama2023_Dataset2_Dataset3_20230416.csv
├── configs/
├── prostab/
└── train.py
Based on the error message _pickle.UnpicklingError: invalid load key, '\x0a', it appears that the ProteinMPNN weight file is corrupted or incomplete.
Please re-download the ProteinMPNN weights.
After re-downloading the weight file, please try running python train.py again.

**Comment by yaow1004** [comment]
Hi, thank you so much! The model training works now!

For my case, I downloaded the ProteinMPNN model weights for ProteinMPNN github, it does not work. I finally downloaded from ThermoMPNN github -- then the ProStab model training successfully started!
